#!/bin/sh

branch(){
    git branch 2>/dev/null | grep -e '^*' | sed -e 's/^* //'
}

for dir in * ; do
    if [ -d $dir/.git ]; then        
        cd $dir
        echo "Executing 'git $*' in $dir (`branch`)"
        git $* || echo "\033[1;31m!!!\033[0m"
        cd - > /dev/null;
    else
        echo "Ignoring $dir: not a git repository"
    fi
done

